src/Entity/Image.php
<?php

namespace App\Entity;

use App\Repository\ImageRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ImageRepository::class)]
class Image
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['read'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read'])]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Groups(['read'])]
    private ?string $filePath = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['read'])]
    private ?string $owner = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups(['read'])]
    private ?DateTimeInterface $created = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['read'])]
    private ?string $cdnUrl = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeInterface $delivered = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['read'])]
    private ?DateTimeInterface $displayed = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['read'])]
    private ?\DateTimeInterface $uploaded = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFilePath(): ?string
    {
        return $this->filePath;
    }

    public function setFilePath(string $filePath): static
    {
        $this->filePath = $filePath;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(?string $owner): Image
    {
        $this->owner = $owner;
        return $this;
    }


    public function getCreated(): ?DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(DateTimeInterface $created): static
    {
        $this->created = $created;

        return $this;
    }

    public function getDisplayed(): ?DateTimeInterface
    {
        return $this->displayed;
    }

    public function setDisplayed(?DateTimeInterface $displayed): static
    {
        $this->displayed = $displayed;

        return $this;
    }

    public function getDelivered(): ?DateTimeInterface
    {
        return $this->delivered;
    }

    public function setDelivered(?DateTimeInterface $delivered): static
    {
        $this->delivered = $delivered;

        return $this;
    }

    public function getCdnUrl(): ?string
    {
        return $this->cdnUrl;
    }

    public function setCdnUrl(?string $cdnUrl): static
    {
        $this->cdnUrl = $cdnUrl;

        return $this;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function updatedTimestamps(): void
    {
        if (is_null($this->getCreated())) {
            $this->setCreated(new DateTime('now'));
        }
    }

    public function getUploaded(): ?\DateTimeInterface
    {
        return $this->uploaded;
    }

    public function setUploaded(?\DateTimeInterface $uploaded): static
    {
        $this->uploaded = $uploaded;

        return $this;
    }

    public function getPath(): ?string
    {
        if (!$this->getCdnUrl()){
            return $this->filePath;
        }
        return $this->cdnUrl;
    }
}

src/Controller/LandingController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Repository\ImageRepository;
use App\Service\Image\ImageService;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LandingController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ImageService $imageService): Response
    {
        $images = $imageService->findAll();
        return $this->render('landing/index.html.twig', [
            'images' => $images,
        ]);
    }

    #[Route('/archive', name: 'app_archive')]
    public function archive(Request $request, PaginatorInterface $paginator, ImageRepository $imageRepository): Response
    {
        $query = $imageRepository->createQueryBuilder('i')->getQuery();

        $images = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1), // Current page number
            10 // Items per page
        );

        return $this->render('landing/archive.html.twig', [
            'images' => $images,
        ]);
    }

    #[Route('/impressum', name: 'app_impressum')]
    public function test(): Response
    {
        return $this->render('landing/impressum.html.twig', [
        ]);
    }
}

templates/landing/archive.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dat koelsch Dreijestirn{% endblock %}

{% block body %}


    <div class="content-body">

        {# templates/image/index.html.twig #}
        <h1>Archive</h1>
        <div class="image-list" id="image-list">

                {% for image in images %}
                    <div class="image-card" data-src="{{ image.path }}">
                        <img src="{{ image.path }}" alt="{{ image.name }}" loading="lazy">
                        <div class="image-details">
                            <p id="name">@{{ image.owner }}</p>
                        </div>
                    </div>
                {% endfor %}
        </div>


        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <img class="modal-content" id="img01">
            <div id="caption"></div>
        </div>

            {{ knp_pagination_render(images) }}




    </div>

    <script>

        var modal = document.getElementById("myModal");

        var images = document.querySelectorAll(".image-card img");

        // Get the image and insert it inside the modal - use its "alt" text as a caption
        images.forEach(function(image) {
            image.onclick = function() {
                // Get the image and insert it inside the modal - use its "alt" text as a caption

                var modalImg = document.getElementById("img01");
                var captionText = document.getElementById("caption");


                modal.style.display = "block";
                modalImg.src = this.src;
                captionText.innerHTML = image.parentElement.outerText;

                // Get the <span> element that closes the modal
                var span = document.getElementsByClassName("close")[0];

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                    modal.style.display = "none";
                }
            };
        });


    </script>
{% endblock %}

templates/landing/impressum.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dat koelsch Dreijestirn{% endblock %}

{% block body %}


    <div class="content-body">
        <h1>Allgemeine Geschäftsbedingungen (AGB)</h1>
        <p><strong>1. Geltungsbereich</strong></p>
        <p>Diese Allgemeinen Geschäftsbedingungen regeln die Nutzung der Website https://www.koelsch-dreijestirn.com (nachfolgend "Website" genannt).</p>

        <p><strong>2. Nutzungsbedingungen</strong></p>
        <ul>
            <li>Die Nutzung der Website unterliegt diesen AGB.</li>
            <li>Benutzer sind dafür verantwortlich, sicherzustellen, dass die von ihnen hochgeladenen Bilder den geltenden Gesetzen entsprechen und keine Rechte Dritter verletzen.</li>
            <li>Die Website kann Benutzern das Recht einräumen, Bilder hochzuladen, zu bearbeiten und zu teilen, unterliegt jedoch den Einschränkungen dieser AGB und den geltenden Gesetzen.</li>
        </ul>

        <p><strong>3. Eigentumsrechte</strong></p>
        <ul>
            <li>Benutzer behalten das Urheberrecht an den von ihnen hochgeladenen Bildern.</li>
            <li>Durch das Hochladen von Bildern auf die Website räumen Benutzer der Website eine nicht-exklusive Lizenz ein, die Bilder im Rahmen der Website zu nutzen, zu bearbeiten und zu teilen.</li>
        </ul>

        <p><strong>4. Haftungsbeschränkungen</strong></p>
        <ul>
            <li>Die Website übernimmt keine Verantwortung für den Inhalt der hochgeladenen Bilder und lehnt jegliche Haftung für Verluste oder Schäden ab, die aus der Nutzung dieser Bilder resultieren.</li>
            <li>Benutzer sind für den Inhalt, den sie hochladen, verantwortlich, und die Website behält sich das Recht vor, Inhalte zu entfernen, die gegen diese AGB verstoßen oder als unangemessen erachtet werden.</li>
        </ul>

        <p><strong>5. Datenschutzrichtlinien</strong></p>
        <p>Die Datenschutzrichtlinien der Website regeln die Verwendung von personenbezogenen Daten der Benutzer und sind integraler Bestandteil dieser AGB.</p>

        <p><strong>6. Urheberrechtsrichtlinien</strong></p>
        <p>Die Website respektiert das geistige Eigentum Dritter und behandelt Beschwerden über Urheberrechtsverletzungen gemäß den geltenden Gesetzen.</p>

        <p><strong>7. Änderungen der AGB</strong></p>
        <p>Die Website behält sich das Recht vor, diese AGB jederzeit ohne vorherige Ankündigung zu ändern. Benutzer werden über wesentliche Änderungen informiert.</p>

        <p><strong>8. Schlussbestimmungen</strong></p>
        <p>Diese AGB unterliegen ausschließlich deutschem Recht.</p>
    </div>
{% endblock %}

templates/landing/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dat koelsch Dreijestirn{% endblock %}

{% block body %}


    <div class="content-body">

        <div class="button-container">
            <div class="button-element">
                <a href="{{ path('app_upload') }}" class="button upload-button" aria-label="Upload">
                    <i class="fas fa-upload"></i>
                </a>
                <span>Sende Grüße</span>
            </div>

            <div class="button-element">
            <a href="/gambling" class="button gambling-button" aria-label="Gambling">
                <i class="fas fa-dice"></i>
            </a>
                Welcher Kölsch-Typ bist du?
            </div>
        </div>


        {#        <div id="image-list">#}
{#            {% for image in images %}#}
{#                <div class="image-card" data-src="{{ image.filePath }}">#}
{#                    <img src="{{ image.cdnUrl }}" alt="{{ image.name }}" loading="lazy">#}
{#                    <div class="image-details">#}
{#                        <p>{{ image.owner }}</p>#}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}

        <p>Unsere Fans:</p>
        <div class="image-list" id="image-list">
            {% for image in images %}
            <div class="image-card" data-src="{{ image.filePath }}">
                <img src="{{ image.filePath }}" alt="{{ image.name }}" loading="lazy">
                <div class="image-details">
                    <p id="name">@{{ image.owner }}</p>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <img class="modal-content" id="img01">
            <div id="caption"></div>
        </div>


    </div>
    <script>

        var modal = document.getElementById("myModal");

        var images = document.querySelectorAll(".image-card img");

        // Get the image and insert it inside the modal - use its "alt" text as a caption
        images.forEach(function(image) {
            image.onclick = function() {
                // Get the image and insert it inside the modal - use its "alt" text as a caption

                var modalImg = document.getElementById("img01");
                var captionText = document.getElementById("caption");


                modal.style.display = "block";
                modalImg.src = this.src;
                captionText.innerHTML = image.parentElement.outerText;

                // Get the <span> element that closes the modal
                var span = document.getElementsByClassName("close")[0];

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                    modal.style.display = "none";
                }
            };
        });






        // document.addEventListener('DOMContentLoaded', function() {
        //     const imageCards = document.querySelectorAll('.image-card');
        //
        //     function lazyLoadImage(imageCard) {
        //         const image = imageCard.querySelector('img');
        //         const src = imageCard.getAttribute('data-src');
        //         if (src) {
        //             image.setAttribute('src', src);
        //             image.onload = function() {
        //                 image.removeAttribute('data-src');
        //             };
        //         }
        //     }
        //
        //     function handleIntersection(entries) {
        //         entries.forEach(entry => {
        //             if (entry.intersectionRatio > 0) {
        //                 lazyLoadImage(entry.target);
        //             }
        //         });
        //     }
        //
        //     const observer = new IntersectionObserver(handleIntersection, {
        //         root: null,
        //         rootMargin: '0px',
        //         threshold: 0.5
        //     });
        //
        //     imageCards.forEach(imageCard => {
        //         observer.observe(imageCard);
        //     });
        //
        //     function showImageInModal(imageSrc) {
        //         const modal = document.createElement('div');
        //         modal.classList.add('modal');
        //         modal.innerHTML = `
        //     <div class="modal-content">
        //         <span class="close">&times;</span>
        //         <img src="${imageSrc}" alt="Image">
        //     </div>
        // `;
        //
        //         document.body.appendChild(modal);
        //
        //         const closeButton = modal.querySelector('.close');
        //         closeButton.addEventListener('click', function() {
        //             document.body.removeChild(modal);
        //         });
        //
        //         const modalContent = modal.querySelector('.modal-content');
        //         modalContent.addEventListener('click', function() {
        //             document.body.removeChild(modal);
        //         });
        //     }
        //
        //     imageCards.forEach(imageCard => {
        //         const image = imageCard.querySelector('img');
        //         image.addEventListener('click', function() {
        //             const src = this.getAttribute('src');
        //             showImageInModal(src);
        //         });
        //     });
        // });

    </script>
{% endblock %}